# Generated by Django 4.2.1 on 2023-05-08 19:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=11)),
                ('mobile_code', models.CharField(blank=True, max_length=10)),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('time_zone', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MailList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(default='')),
                ('mobile_code_filter', models.CharField(blank=True, max_length=10)),
                ('tag_filter', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAIL', 'Fail'), ('WAIT', 'Wait')], default='WAIT', max_length=20)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='messages_api.client')),
                ('mail_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='messages_api.maillist')),
            ],
        ),
    ]
